// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQMAOrM44chWAVpfbP6O_efQeKRz32Rg',
    appId: '1:680863848651:web:f4bf14483fe87ce701a34e',
    messagingSenderId: '680863848651',
    projectId: 'message-7798d',
    authDomain: 'message-7798d.firebaseapp.com',
    storageBucket: 'message-7798d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGYroqTdXSvxOrLxUOMHdHCjGcPputDlc',
    appId: '1:680863848651:android:4b2807926637df1c01a34e',
    messagingSenderId: '680863848651',
    projectId: 'message-7798d',
    storageBucket: 'message-7798d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZQMAOrM44chWAVpfbP6O_efQeKRz32Rg',
    appId: '1:680863848651:web:09da237f2561037401a34e',
    messagingSenderId: '680863848651',
    projectId: 'message-7798d',
    authDomain: 'message-7798d.firebaseapp.com',
    storageBucket: 'message-7798d.appspot.com',
  );
}
